package project1;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fahim
 */
public class ViewAllItems extends javax.swing.JFrame
{

    /**
     * Creates new form ViewAllItems
     */
    public ViewAllItems()
    {
        initComponents();
        
        ArrayList<Product> productList = new ArrayList<Product>();
        
        MeatReader meatReader = new MeatReader();
        ArrayList<Product> meatList = meatReader.getMeats();
        productList.addAll(meatList);

        FruitReader fruitReader = new FruitReader();
        ArrayList<Product> fruitList = fruitReader.getFruit();
        productList.addAll(fruitList);

        VegetableReader vegetableReader = new VegetableReader();
        ArrayList<Product> vegetableList = vegetableReader.getVegetable();
        productList.addAll(vegetableList);
        
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < productList.size(); i++)
        {
            listModel.addElement(productList.get(i));
        }
        itemList.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        viewAllItems = new javax.swing.JPanel();
        viewCartButton = new javax.swing.JButton();
        checkoutButton = new javax.swing.JButton();
        mainmenuButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        meatButton = new javax.swing.JButton();
        vegetableButton = new javax.swing.JButton();
        fruitButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        addToCartButton = new javax.swing.JButton();
        allItemsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        allItems = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewCartButton.setText("View Cart");
        viewCartButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                viewCartButtonActionPerformed(evt);
            }
        });

        checkoutButton.setText("Checkout");

        mainmenuButton.setText("Main menu");
        mainmenuButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mainmenuButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitButtonActionPerformed(evt);
            }
        });

        meatButton.setText("Meat");
        meatButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                meatButtonActionPerformed(evt);
            }
        });

        vegetableButton.setText("Vegetable");
        vegetableButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vegetableButtonActionPerformed(evt);
            }
        });

        fruitButton.setText("Fruit");
        fruitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fruitButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");

        addToCartButton.setText("Add to cart");
        addToCartButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addToCartButtonActionPerformed(evt);
            }
        });

        allItemsLabel.setText("All Items");

        itemList.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(itemList);

        jLabel1.setText("Categories");

        allItems.setText("All Items");
        allItems.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                allItemsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewAllItemsLayout = new javax.swing.GroupLayout(viewAllItems);
        viewAllItems.setLayout(viewAllItemsLayout);
        viewAllItemsLayout.setHorizontalGroup(
            viewAllItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllItemsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(viewAllItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(allItemsLabel))
                .addGap(179, 179, 179))
            .addGroup(viewAllItemsLayout.createSequentialGroup()
                .addGroup(viewAllItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewAllItemsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(viewAllItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mainmenuButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewCartButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkoutButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exitButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(viewAllItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllItemsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                                .addComponent(addToCartButton))))
                    .addGroup(viewAllItemsLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(allItems)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(meatButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vegetableButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fruitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        viewAllItemsLayout.setVerticalGroup(
            viewAllItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewAllItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allItemsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewAllItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meatButton)
                    .addComponent(vegetableButton)
                    .addComponent(fruitButton)
                    .addComponent(allItems))
                .addGroup(viewAllItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewAllItemsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewCartButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mainmenuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitButton)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllItemsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)))
                .addGroup(viewAllItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewAllItemsLayout.createSequentialGroup()
                        .addComponent(searchButton)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllItemsLayout.createSequentialGroup()
                        .addComponent(addToCartButton)
                        .addGap(14, 14, 14))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(viewAllItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(viewAllItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewCartButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_viewCartButtonActionPerformed
    {//GEN-HEADEREND:event_viewCartButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("asdfsadfsad");
    }//GEN-LAST:event_viewCartButtonActionPerformed

    private void mainmenuButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mainmenuButtonActionPerformed
    {//GEN-HEADEREND:event_mainmenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainmenuButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitButtonActionPerformed
    {//GEN-HEADEREND:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addToCartButtonActionPerformed
    {//GEN-HEADEREND:event_addToCartButtonActionPerformed

    }//GEN-LAST:event_addToCartButtonActionPerformed

    private void meatButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_meatButtonActionPerformed
    {//GEN-HEADEREND:event_meatButtonActionPerformed
        itemList.removeAll();
        MeatReader meatReader = new MeatReader();
        ArrayList<Product> meatList = meatReader.getMeats();
        
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < meatList.size(); i++)
        {
            listModel.addElement(meatList.get(i));
        }
        itemList.setModel(listModel);
    }//GEN-LAST:event_meatButtonActionPerformed

    private void allItemsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_allItemsActionPerformed
    {//GEN-HEADEREND:event_allItemsActionPerformed
        itemList.removeAll();
        ArrayList<Product> productList = new ArrayList<Product>();
        MeatReader meatReader = new MeatReader();
        ArrayList<Product> meatList = meatReader.getMeats();
        productList.addAll(meatList);

        FruitReader fruitReader = new FruitReader();
        ArrayList<Product> fruitList = fruitReader.getFruit();
        productList.addAll(fruitList);

        VegetableReader vegetableReader = new VegetableReader();
        ArrayList<Product> vegetableList = vegetableReader.getVegetable();
        productList.addAll(vegetableList);
        
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < productList.size(); i++)
        {
            listModel.addElement(productList.get(i));
        }
        itemList.setModel(listModel);
    }//GEN-LAST:event_allItemsActionPerformed

    private void vegetableButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vegetableButtonActionPerformed
    {//GEN-HEADEREND:event_vegetableButtonActionPerformed
        itemList.removeAll();

        VegetableReader vegetableReader = new VegetableReader();
        ArrayList<Product> vegetableList = vegetableReader.getVegetable();
        
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < vegetableList.size(); i++)
        {
            listModel.addElement(vegetableList.get(i));
        }
        itemList.setModel(listModel);
    }//GEN-LAST:event_vegetableButtonActionPerformed

    private void fruitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fruitButtonActionPerformed
    {//GEN-HEADEREND:event_fruitButtonActionPerformed
        FruitReader fruitReader = new FruitReader();
        ArrayList<Product> fruitList = fruitReader.getFruit();
        
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < fruitList.size(); i++)
        {
            listModel.addElement(fruitList.get(i));
        }
        itemList.setModel(listModel);
    }//GEN-LAST:event_fruitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ViewAllItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ViewAllItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ViewAllItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ViewAllItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ViewAllItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartButton;
    private javax.swing.JButton allItems;
    private javax.swing.JLabel allItemsLabel;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton fruitButton;
    private javax.swing.JList<String> itemList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainmenuButton;
    private javax.swing.JButton meatButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton vegetableButton;
    private javax.swing.JPanel viewAllItems;
    private javax.swing.JButton viewCartButton;
    // End of variables declaration//GEN-END:variables
}
